###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://ory-am.gitbooks.io/hydra/content/tutorial.html                 #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

version: '2'

services:

  hydra-migrate:
    image: hydra_hydra-migrate:latest
    links:
      - postgresd:postgresd
    networks:
      - intranet
    environment:
      - LOG_LEVEL=debug
      - HYDRA_SYSTEM_SECRET=youReallyNeedToChangeThis
    command:
      migrate sql postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    restart: on-failure

  hydra:
    image: hydra_hydra:latest
    links:
      - postgresd:postgresd
    ports:
      - "4444:4444"
      - "4445:4445"
    depends_on:
      - hydra-migrate
    command:
      serve all --dangerous-force-http
    networks:
      - intranet
    environment:
      - LOG_LEVEL=debug
      - SYSTEM_SECRET=youReallyNeedToChangeThis
      - DATABASE_URL=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
      - OAUTH2_CONSENT_URL=http://$BROWSER_IDP_HOST:4488/consent
      - OAUTH2_LOGIN_URL=http://$BROWSER_IDP_HOST:4488/login
      - OAUTH2_ISSUER_URL=http://$BROWSER_HYDRA_HOST:4444
      - OAUTH2_SHARE_ERROR_DEBUG=1
    restart: on-failure

  configurator:
    build:
      context: ../
      dockerfile: full-stack/Dockerfile
      args:
        - HYDRA_VERSION=$HYDRA_VERSION
    depends_on:
      - hydra
    networks:
      - intranet
    environment:
      # All of these URLs MUST NOT end with a trailing slash. This is very important!
      - HYDRA_URL=http://hydra:4444
      - HYDRA_ADMIN_URL=http://hydra:4445
      - RESOURCE_SERVER_URL=http://resource-server:4478
      
      # This sets the prefix for all resource, action, and subject names. Be aware that this prefix is automatically
      # applied to all OAuth2 Clients as well.
      - "HYDRA_SUBJECT_PREFIX=subjects:hydra:"
      - "HYDRA_RESOURCE_PREFIX=resources:hydra:"
      - "HYDRA_ACTION_PREFIX=actions:hydra:"
      
    restart: on-failure

  identity-provider:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PORT=4488
    image: oryd/hydra-login-consent-node:$LOGIN_CONSENT_VERSION
    networks:
      - intranet
    ports:
      - "4488:4488"
    restart: on-failure

  # This ".localhost" hack allows us to use http:// in the tests, because hydra only allows http:// on callback urls
  # for localhost and *.localhost
  "consumer.localhost":
    build:
      context: ../apps/consumer
      dockerfile: Dockerfile
    networks:
      - intranet
    depends_on:
      - hydra
    ports:
      - "4477:4477"
    environment:
      - PORT=4477
      - OAUTH2_AUTH_URL=http://$BROWSER_HYDRA_HOST:4444/oauth2/auth
      - OAUTH2_TOKEN_URL=http://hydra:4444/oauth2/token
      - OAUTH2_CLIENT_ID=consumer-app
      - OAUTH2_CLIENT_SECRET=consumer-secret
      - OAUTH2_REDIRECT_URL=http://$BROWSER_CONSUMER_HOST:4477/auth/callback
      - BACKEND_INTROSPECT_URL=http://resource-server:4478/introspect

  resource-server:
    build:
      context: ../apps/resource-server
      dockerfile: Dockerfile
    depends_on:
      - hydra
    networks:
      - intranet
    ports:
      - "4478:4478"
    environment:
      - PORT=4478
      - OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect
      - nodemon start

  postgresd:
    image: postgres:9.6
    networks:
      - intranet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb

networks:
  intranet:
    driver: bridge
